Camera:
  Focal: 13.971313932573906
  High: 650.0
Center:
  Camera_high: 620
<<<<<<< HEAD
  Center_X: 327
  Center_Y: 253
  Front: 90
  Horizon: 144
  Inner: 54
  Outer: 282
=======
  Center_X: 318
  Center_Y: 258
  Front: 91
  Horizon: 134
  Inner: 44
  Outer: 229
>>>>>>> bf346f0f13baa2929a17737eb9455f821da98053
  X: 308
  Y: 266
FPS: 16
HSV:
  Ball:
  - 0
  - 26
  - 30
  - 100
  - 18
  - 100
  Blue:
  - 213
  - 261
  - 53
  - 100
  - 48
  - 99
  Green:
  - 150
  - 213
  - 51
  - 96
  - 17
  - 98
  White:
  - 197
  - 168
  - 0
  - 79
  - 0
  - 23
  Yellow:
  - 39
  - 79
  - 10
  - 100
  - 56
  - 100
  black:
    angle: 1
    gray: 30
  white:
    angle: 3
    gray: 193
Parameterbutton: 4
SCAN:
  Angle_Near_Gap: 4
  Angle_range_1: 2
  Angle_range_2_3: 2
<<<<<<< HEAD
  Dont_Search_Angle_1: 32
  Dont_Search_Angle_2: 151
  Dont_Search_Angle_3: 267
=======
  Dont_Search_Angle_1: 30
  Dont_Search_Angle_2: 150
  Dont_Search_Angle_3: 276
>>>>>>> bf346f0f13baa2929a17737eb9455f821da98053
  Magn_Far_End: 224
  Magn_Far_Start: 154
  Magn_Middle_Start: 50
  Magn_Near_Gap: 3
  Magn_Near_Start: 35
blackItem:
  angle: 3
  gray: 40
whiteline:
  angle: 4
  gray: 100
